### ISSUE TITLE
[Questions] More details about the tool

### ISSUE THREAD

**Issue by ducalpha** [ITSec-WWU-Munster/Unifying-Privacy-Policy-Detection#1]
Thank you for the great tool. I still have some questions after reading through the `README.md`:

1. Could you provide more description about how to run the tool? 
2. Is the input of the tool an HTML or URL of a website? 
3. Could you provide an example how to run the tool from end to end (from fresh environment to the output of the program)?

**Comment by g3rfx** [comment]
Hi,

We are currently working on porting the toolchain to a Vagrant box. 

Currently, the tool expects downloaded HTML files in the `data\crawl` folder as the link detection module has not been uploaded yet. 

We will include an example in the Vagrant box.
